### ISSUE TITLE
nextcloud.manual-install ignoring directory in autoconfig.php

### ISSUE THREAD

**Issue by jorkzijlstra** [nextcloud/nextcloud-snap#1670]
#### Describe the bug
A clear and concise description of the bug.

#### To Reproduce
I'm using ansible to setup my new server and I wanted to move the data directory. I thought I'd use this manual to do so:
https://github.com/nextcloud/nextcloud-snap/wiki/Change-data-directory-to-use-another-disk-partition

I found that when using the manual-install command it does not seem to be using the `directory` property in the autoconfig.php.
But when using the admin account http page it does work.

Ansible script that won't use the directory:
```
- name: Check if Nextcloud is already installed.
  shell: "nextcloud.occ status"
  args:
    warn: no
  register: nextcloud_installed
  changed_when: false
  failed_when:
    - nextcloud_installed.rc == 0
    - "'nextcloud.occ: not found' in nextcloud_installed.stderr"

- name: "Setting directory ownership & permissions for the data folder"
  file:
    path: "{{ nextcloud_data_dir }}"
    mode: "0770"
    recurse: yes
    state: directory
    owner: "{{ nextcloud_websrv_user }}"
    group: "{{ nextcloud_websrv_group }}"
  when: 
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Install nextcloud from snapcraft
  shell: snap install nextcloud
  when:
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Configure nextcloud removable-media from snapcraft
  shell: snap connect nextcloud:removable-media
  when:
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Restart Nextcloud
  shell: snap restart nextcloud
  when:
    - nextcloud_state | default('present') == 'present'
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Wait until the config file is present before continuing
  wait_for:
    path: "/var/snap/nextcloud/current/nextcloud/config/autoconfig.php"
  when:
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Update Nextcloud configuration.
  lineinfile:
    dest: "/var/snap/nextcloud/current/nextcloud/config/autoconfig.php"
    line: "'{{ item.name }}' => '{{ item.value }}',"
    regexp: "^'{{ item.name }}' =>"
  with_items:
    - name: directory
      value: "{{ nextcloud_data_dir }}"
  when:
    - nextcloud_state | default('present') == 'present'
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Restart nextcloud.php-fpm
  shell: snap restart nextcloud.php-fpm
  when:
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"

- name: Setup nextcloud data dir on the system
  shell: nextcloud.occ config:system:set directory --value="{{ nextcloud_data_dir }}"
  when:
    - nextcloud_state | default('present') == 'present'
  notify:
    - nextcloud restart
```

Workaround:
Replacing the manual-install step with a post on the index.php page to create the admin account does work
```
- name: Trigger admin account creation
  uri:
    url: http://{{ ansible_host }}/index.php
    method: POST
    body_format: form-urlencoded
    body:
      install: true
      adminlogin: "{{ nextcloud_AdminUsername }}"
      adminpass: "{{ nextcloud_AdminPassword }}"
      adminpass-clone: admin
    timeout: 120
    status_code: 302
  register: login
  when:
    - nextcloud_state | default('present') == 'present' 
    - "'installed: true' not in nextcloud_installed.stdout"
```

#### Expected behavior
The `directory` property from the autoconfig.php to be used.

#### OS/snapd/snap version
What OS and version are you running? Please also include the output of the
following commands: 

    $ snap list nextcloud

```
nextcloud  20.0.7snap1  26119  latest/stable  nextcloud✓  -
```

and:

    $ snap version

```
snap    2.49
snapd   2.49
series  16
ubuntu  20.04
kernel  5.4.0-66-generic

```
